# Generated by Django 5.1.1 on 2026-05-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание')),
                ('category', models.CharField(choices=[('outerwear', 'Outerwear'), ('capsule', 'Capsule'), ('drop', 'Drop'), ('merch', 'Merch')], default='drop', max_length=20, verbose_name='Категория')),
                ('image', models.ImageField(upload_to='works/', verbose_name='Фото')),
                ('card_size', models.CharField(choices=[('normal', 'Обычная'), ('wide', 'Широкая (2 колонки)')], default='normal', max_length=10, verbose_name='Размер карточки')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
